# Generated by Django 5.1 on 2025-07-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_block_unit_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
